---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fastapi-spark-launcher
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sparkapplication-creator
  namespace: default
rules:
  - apiGroups: ["sparkoperator.k8s.io"]
    resources: ["sparkapplications"]
    verbs: ["create", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fastapi-launcher-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: fastapi-spark-launcher
    namespace: default
roleRef:
  kind: Role
  name: sparkapplication-creator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-spark-launcher
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-spark-launcher
  template:
    metadata:
      labels:
        app: fastapi-spark-launcher
    spec:
      serviceAccountName: fastapi-spark-launcher
      containers:
        - name: api
          image: docker.io/gmaas2/spark-launcher:1.3
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-spark-launcher
  namespace: default
spec:
  selector:
    app: fastapi-spark-launcher
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000