apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-astronauts
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: docker.io/gmaas2/spark-astronauts-jobs:1.2
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/spark/jobs/astronauts.py
  sparkVersion: 3.5.3
  restartPolicy:
    type: Never
  driver:
    cores: 1
    memory: 512m
    serviceAccount: spark-operator-spark
  executor:
    cores: 1
    instances: 1
    memory: 512m